import AppKit

// Restauration du presse-papiers après le collage (MURMURE_RESTORE_CLIPBOARD=1).
// murmure.sh appelle l'exécutable de l'app, sans interface :
//   Murmure --presse-papiers remplacer FICHIER   (texte de la dictée sur stdin)
//   Murmure --presse-papiers restaurer FICHIER
// « remplacer » sauvegarde le contenu actuel dans FICHIER, tous types compris
// (texte, RTF, images, fichiers…), puis y met la dictée ; « restaurer » remet la
// sauvegarde, sauf si le presse-papiers a changé depuis, et efface FICHIER.
//
// Limites : les données sont lues au moment de la sauvegarde. Un contenu
// fourni à la demande par l'app d'origine (grosse image, formats d'Office) est
// donc produit tout de suite, et après restauration cette app n'en est plus la
// propriétaire : les options qui en dépendent (collage spécial lié) peuvent
// disparaître. Un type illisible est ignoré s'il reste à l'élément un autre type
// (le système en déduit certains, comme le texte UTF-16 du texte UTF-8) ; un
// élément sans aucun type lisible fait tout abandonner : la dictée reste au
// presse-papiers plutôt qu'un contenu tronqué.
enum PressePapiers {
    // Au-delà, on renonce : sauvegarder retarderait le collage.
    static let tailleMax = 64 << 20
    // Contenus marqués par les gestionnaires de mots de passe
    // (nspasteboard.org) : les remettre prolongerait leur présence, car
    // l'effacement programmé ne reconnaîtrait plus son propre contenu.
    static let sensibles: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                                         "org.nspasteboard.AutoGeneratedType"]

    // MURMURE_CLIPBOARD_NAME désigne un presse-papiers nommé : réservé aux essais,
    // pour ne jamais toucher celui de l'utilisateur.
    static var tableau: NSPasteboard {
        if let nom = ProcessInfo.processInfo.environment["MURMURE_CLIPBOARD_NAME"], !nom.isEmpty {
            return NSPasteboard(name: NSPasteboard.Name(nom))
        }
        return .general
    }

    static func ligneDeCommande(_ args: [String]) -> Int32 {
        guard args.count == 2 else {
            journal("usage : --presse-papiers remplacer|restaurer FICHIER")
            return 2
        }
        switch args[0] {
        case "remplacer": return remplacer(args[1])
        case "restaurer": restaurer(args[1]); return 0
        default:
            journal("presse-papiers : commande inconnue « \(args[0]) »")
            return 2
        }
    }

    // Sauvegarde puis écrit la dictée. Code 0 dès que la dictée est écrite,
    // même sans sauvegarde : le script ne restaure que si FICHIER existe.
    private static func remplacer(_ fichier: String) -> Int32 {
        let pb = tableau
        try? FileManager.default.removeItem(atPath: fichier)
        let donnees = FileHandle.standardInput.readDataToEndOfFile()
        let texte = String(decoding: donnees, as: UTF8.self)
        let sauvegarde = sauvegarder(pb)

        pb.clearContents()
        guard pb.setString(texte, forType: .string) else {
            journal("presse-papiers : écriture de la dictée impossible")
            return 1
        }
        guard var s = sauvegarde else { return 0 }
        s["compteur"] = pb.changeCount   // état juste après la dictée
        do {
            let plist = try PropertyListSerialization.data(fromPropertyList: s, format: .binary, options: 0)
            // Contenu privé : lisible par l'utilisateur seul.
            guard FileManager.default.createFile(atPath: fichier, contents: plist,
                                                 attributes: [.posixPermissions: 0o600]) else {
                throw CocoaError(.fileWriteUnknown)
            }
        } catch {
            journal("presse-papiers : sauvegarde non écrite (\(error.localizedDescription))")
        }
        return 0
    }

    // Tous les éléments et tous leurs types, dans l'ordre de préférence ; nil
    // si le contenu ne doit pas ou ne peut pas être restauré fidèlement.
    private static func sauvegarder(_ pb: NSPasteboard) -> [String: Any]? {
        let items = pb.pasteboardItems ?? []
        if items.isEmpty {
            journal("presse-papiers vide : la dictée y restera")
            return nil
        }
        if items.contains(where: { $0.types.contains { sensibles.contains($0.rawValue) } }) {
            journal("presse-papiers marqué confidentiel ou temporaire : pas de restauration")
            return nil
        }
        var elements: [[[String: Any]]] = []
        var total = 0, ignores: [String] = []
        for item in items {
            var types: [[String: Any]] = []
            for type in item.types {
                guard let data = item.data(forType: type) else { ignores.append(type.rawValue); continue }
                total += data.count
                if total > tailleMax {
                    journal("presse-papiers : contenu de plus de \(tailleMax >> 20) Mo, pas de restauration")
                    return nil
                }
                types.append(["type": type.rawValue, "data": data])
            }
            // Accès refusé par l'utilisateur (alerte de macOS à la lecture du
            // presse-papiers) ou contenu que l'app d'origine ne fournit plus.
            guard !types.isEmpty else {
                journal("presse-papiers illisible (\(item.types.map(\.rawValue).joined(separator: ", "))) : pas de restauration")
                return nil
            }
            elements.append(types)
        }
        if !ignores.isEmpty { journal("presse-papiers : types illisibles ignorés : \(ignores.joined(separator: ", "))") }
        journal("presse-papiers sauvegardé (\(elements.count) élément(s), \(total) octets)")
        return ["elements": elements]
    }

    private static func restaurer(_ fichier: String) {
        defer { try? FileManager.default.removeItem(atPath: fichier) }
        guard let plist = FileManager.default.contents(atPath: fichier),
              let s = try? PropertyListSerialization.propertyList(from: plist, format: nil) as? [String: Any],
              let compteur = s["compteur"] as? Int,
              let elements = s["elements"] as? [[[String: Any]]] else {
            journal("presse-papiers : sauvegarde illisible, pas de restauration")
            return
        }
        let pb = tableau
        // Copie faite entre-temps (par l'utilisateur ou une app) : elle prime.
        guard pb.changeCount == compteur else {
            journal("presse-papiers modifié depuis la dictée : pas de restauration")
            return
        }
        let items: [NSPasteboardItem] = elements.map { types in
            let item = NSPasteboardItem()
            for t in types {
                if let type = t["type"] as? String, let data = t["data"] as? Data {
                    item.setData(data, forType: NSPasteboard.PasteboardType(type))
                }
            }
            return item
        }
        pb.clearContents()
        if pb.writeObjects(items) {
            journal("presse-papiers restauré (\(items.count) élément(s))")
        } else {
            journal("presse-papiers : restauration refusée par le système")
        }
    }
}
